name: Update Readme
on:
  schedule:
    - cron : '15 */4 * * 1-5'
  
jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run weather updater
        run: go run weather/main.go
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update weather information in README.md
          branch: main